### ISSUE TITLE
unable to download tidyLPA package from GitHub

### ISSUE THREAD

**Issue by cavaughan99** [jrosen48/tidyLPA#11]
Hello,

I would like to use tidyLPA but get the following error message when I try to download it on my PC:

Warning in gzfile(file, "rb") :
  cannot open compressed file 'C:/Users/cvaughan/Documents/desktop.m.rds', probable reason 'No such file or directory'
Error in gzfile(file, "rb") : cannot open the connection
Error : unable to load R code in package 'tidyLPA'
ERROR: lazy loading failed for package 'tidyLPA'

I tried downloading the package on my personal Mac and got the same error message, so I don't think there is a firewall issue with my PC as related posts on stackexchange about the "cannot open the connection" error message have suggested. If you have a remedy for this problem, I would be very interested in it. Thank you in advance!

**Comment by jrosen48** [comment]
Christine - so sorry that I missed this! Please let me know if, using `devtools::install_github("jrosen48/tidyLPA"), you can now install the package. I apologize for the inconvenience and hope that some minor changes fixed this unfortunate issue!

**Comment by jrosen48** [comment]
Fixed (via email correspondence)
