### ISSUE TITLE
Continuous variables

### ISSUE THREAD

**Issue by oreojo** [jrosen48/tidyLPA#40]
Hi,

This isn't an issue as such, but it might be worth making it explicit that the package works best for continuous variables. I have 6 variables that are ordinal I suppose, at best - effectively a range of 1 - 12, in increments of 1, but with little variation (ie. a lot of people score 1, 6 or 12). 

Originally I was using LPA because I thought it'd accommodate the data, but it's not best suited to it. The package gives info like 'model couldn't be fitted', and it took me ages to work out why. Totally my fault.

**Comment by jrosen48** [comment]
@oreojo thanks so much for pointing this out - I will add a note in the vignette about this. Leaving this open until then.

**Comment by jrosen48** [comment]
Added this note to the vignette: "Note that LPA works best with continuous variables (and, in some cases, ordinal variables), but is not appropriate for dichotomous (binary) variables."
