### ISSUE TITLE
plot_profiles() with more than nine variables

### ISSUE THREAD

**Issue by MarkusTMattsson** [jrosen48/tidyLPA#48]
plot_profiles() currently uses 

`scale_fill_brewer("", type = "qual", palette = 6)`

to choose the colors for the profiles, which means it works as it should for up to nine different variables. To accommodate models with more variables, could this be changed to use something like 

```
colourCount <- length(x-2)
getPalette <- colorRampPalette(brewer.pal(9, "Set1"))
pal <- getPalette(colourCount)
```

and then 

```
ggplot(aes_string(x = "profile", y = "mean", fill = pal, ymin = "ymin", ymax = "ymax")) + 
                    geom_col(position = "dodge") + geom_errorbar(position = position_dodge()) + 
                    scale_x_discrete("") + theme_bw()
```

The syntax I'm suggesting is probably a bit silly, but I hope my request is understandable. I'm talking about the approach taken at https://www.r-bloggers.com/how-to-expand-color-palette-with-ggplot-and-rcolorbrewer/

**Comment by jrosen48** [comment]
Thank you for this helpful comment and solution. I will try to work on this in the next month.

**Comment by jrosen48** [comment]
This is fixed in the latest version on GitHub and the version soon to be submitted to CRAN. Thanks so much for your input on this.
