### ISSUE TITLE
bootstrap_lrt error

### ISSUE THREAD

**Issue by StuEdward** [jrosen48/tidyLPA#49]
Hello,

I get the following error when running the bootstrap_lrt function: 
Error in txtProgressBar(min = 0, max = (max(G) - 1) * nboot, style = 3) : 
  must have 'max' > 'min'

I'm running the following code:
bootstrap_lrt (df, var1, var2, n_profiles=5, model="VVV")

I would appreciate any comments on this error. Thank you!

**Comment by jrosen48** [comment]
Thank you for this issue. I'm not sure what is causing that; I will poke around the code. The naming convention for the model type is, I'm now aware (see Google Groups post [here](https://groups.google.com/forum/#!topic/tidylpa/lGlE0stRHKE), problematic, and I'm wondering if that is contributing to the problem. Did any changes you have made in the meantime help this to work?

**Comment by jrosen48** [comment]
I updated the naming scheme I mentioned above; please do let me know if this persists and I'll do what I can do help!
