### ISSUE TITLE
Error: package or namespace load failed for ‘tidyLPA’

### ISSUE THREAD

**Issue by RFTindle** [jrosen48/tidyLPA#50]
Error: package or namespace load failed for ‘tidyLPA’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.1.6 is already loaded, but >= 0.2.0 is required
In addition: Warning message:
package ‘tidyLPA’ was built under R version 3.4.4

**Comment by jrosen48** [comment]
Hi, hmm, that is a bit concerning; I'm wondering if we need to update our dependencies for rlang. Did any changes you make resolve this? Thanks!

**Comment by jrosen48** [comment]
I'm updating the package now; please let me know if this problem persists.
