### ISSUE TITLE
typo in estimate_profiles_mplus.R

### ISSUE THREAD

**Issue by gbiele** [jrosen48/tidyLPA#55]
line 132 in estimate_profiles_mplus.R is 
`ANALYSIS_line2 <- paste0("start = ", starts[1], " ", starts[2], ";")`
but it should be 
`ANALYSIS_line2 <- paste0("starts = ", starts[1], " ", starts[2], ";")`
("start**s** ="  not "start  =")

also, nice package!

**Comment by jrosen48** [comment]
Fixed in latest commit to devel version! Thanks @gbiele!
