### ISSUE TITLE
add information  to data.frame/tibble with class probabilities returned from estimate_profiles_mplus

### ISSUE THREAD

**Issue by gbiele** [jrosen48/tidyLPA#57]
when one requests class probabilities from `estimate_profiles_mplus` by setting `return_save_data = R`, information about the model fit like BIC is currently not returned.

It would be useful if this information could be added to the tibble/data.frame with the class probabilities as an attribute, for instance by adding these lines of code the estimate_profiles_mplus.R, just before the tibble is returned (around line 335): 

```
}
        fit_stats = c("LL","BIC","aBIC","AIC","Entropy")
        fs = rep(NA,length(fit_stats))
        names(fs) = fit_stats
        available_fit_stats = intersect(names(m$summaries),fit_stats)
        for (s in available_fit_stats)
            fs[s] = m$summaries[,s]
        attr(x,"fit_stats") = fs
        attr(x,"mplus_warnings") = m$warnings
        attr(x,"mplus_errors") = m$errors
```

**Comment by jrosen48** [comment]
Thanks so much-let me look into this.

**Comment by jrosen48** [comment]
Actually - would you make a pull request with this addition? This looks like a great approach and fix to this.
