### ISSUE TITLE
Consistency of auto-generated mplus models with description in intro to tidyLPA

### ISSUE THREAD

**Issue by gbiele** [jrosen48/tidyLPA#59]
In the [Intro to tidyLPA](https://jrosen48.github.io/tidyLPA/articles/Introduction_to_tidyLPA.html) the models 1 through 6 are described as follows:

1. ... equal variances, and covariances fixed to 0 (model 1)
2. ... equal variances, and equal covariances (model 2)
3. ... varying variances, and covariances fixed to 0 (model 3)
4. ... varying variances, and equal covariances (model 4)
5. ... equal variances, and varying covariances (model 5)
6. ... varying variances, and varying covariances (model 6)

IT looks to me as if the naming used in `estimate_profiles_mplus` is inconsistent with this description. In particular, in `estimate_profiles_mplus`

`model = 1` gives ... equal variances, and covariances ***[OK]***
`model = 2` gives ... varying variances, and covariances fixed to 0 ***[should be model 3]***
`model = 3` gives ... equal variances, and equal covariances ***[should be model 2]***
`model = 4` gives ... varying variances, and varying covariances ***[should be model 6]***

models 4 and 5 are not defined in `estimate_profiles_mplus`.

**Comment by gbiele** [comment]
In [this repository](https://github.com/gbiele/tidyLPA) I have update `estimate_profiles_mplus.R` and `helper.R` to generate all models (1-6) and use model numbers consistent with the Intro to tidyLPA.

Two new helper functions for generating the mplus code to  define the parameterization of variances and covariances make the code for auto-generation of mplus-code a bit more transparent.

**Comment by jrosen48** [comment]
@gbiele thanks so much. You took a lot of time to fix this / work on this and I'm extremely excited and grateful. I hadn't updated the site but was in the process of *reducing* the number of models from 6 to 4. I should have done this on a branch other than master-or have finished updating the site. Let me try to lay out my reasoning: what are *presently* models 4 and 5 are quite esoteric. Also, they cannot be estimated in mclust. Moreover, a colleague of mine attended a mixture modeling workshop recently, and only the four (what are models 1, 3, 2, and 6, corresponding as you noted to models 1-4). What do you think about the importance of those models? 

In terms of the helper functions - thanks. That needed to be done. This code was sort of a first attempt that ended up working *well enough* :) that we never changed it. But it's hard to modify and I concur isn't transparent.

Welcome to the development team! Can you join the mailing list at tidyLPA@googlegroups.com (link to page [here](https://groups.google.com/forum/#!forum/tidylpa?)?

Tagging @datalorax and @cjvanlissa into this.
Thank

**Comment by gbiele** [comment]
Hi Joshua,
I am not big into LPA modeling, so take my opinion with a grain of salt:
I think models 4 and 5 are as relevant as model 6. The key question for me is mainly, if it is possible to recover class member-ships (and mean and (co)variances of the groups) for a given data set, I think this will be difficult for models 4 and 5, but even more difficult for model 6. 

It would be worth the effort to simulate data from data-generating processes implied by models 1-6 and then to see if one can recover class membership etc correctly. Those models for which this is possible I would consider most worthy of inclusion. (I would not be surprised if there already exist papers who did this). An interesting thing which is probably not done is to compare if mclust or mplus are better at recovering class membership etc.

More generally, I like how you laid out the models in your intro. and ultimately I would probably keep them in, but add that the most complex models (with varying variances and covariances) are less stable than the other models. [this can already be observed now, as mplus has more difficulties replicating LLs for those].

I can join the mailing list, but I can't promise that I'll be very involved.
I just implemented this this morning, because I needed it for a project and it was a fun way to procrastinate ;-).
guido

**Comment by cjvanlissa** [comment]
With regard to Guido's comment, I would caution against the notion of 'correctly recovering' class memberships. To me, this sounds a lot like just interpreting the most likely posterior class membership as an observed variable. The literature is quite clear that you should always take classification uncertainty into account. A latent class variable is just a latent variable, but a categorical one. You wouldn't speak of "correctly recovering" somebody's true score on a latent variable for intelligence, for instance, and most people would be skeptical of just exporting the estimated latent variable scores to treat them as an observed variable.

Guido's suggestion to assess the sensitivity of a confirmatory latent class analysis using simulation is a great idea, but it's not clear what to do when the number of classes is not known a-priori!

There should be no difference between Mplus and mclust when using the EM estimator for both, except for trivial reasons.

Models with varying variances and covariances are usually less stable, and the way this is commonly dealt with in Mplus is to 1) increase the number of starts, 2) specify starting values, 3) specify starting values such that the largest class will be the last one (with the highest class number). I think only the first solution is easy to automate.

**Comment by datalorax** [comment]
> You wouldn't speak of "correctly recovering" somebody's true score on a latent variable for intelligence

I'm a little confused by this comment. This sort of thing is done all the time. It's just a way to dig into the model a little more and evaluate things like the standard errors and CI coverage. In IRT, where I work more regularly, people will often set up simulation studies to see if, for example, ability estimates are within a 95% CI 95% of the time with various models and scenarios (or item discriminations or difficulties). I'm not sure I see the difference here, but maybe I'm missing something.

**Comment by cjvanlissa** [comment]
@datalorax let's stay focused on the categorical latent variable case, where you cannot have a confidence interval for group membership. I'm cautioning about the practice of treating class membership as an observed variable, by assigning each case to the class for which the posterior probability is highest. This approach ignores classification uncertainty. Here are three references that address the issue: 
https://www.cambridge.org/core/journals/political-analysis/article/latent-class-modeling-with-covariates-two-improved-threestep-approaches/7DEF387D6ED4CF0A26A2FA06F9470D02
https://www.tandfonline.com/doi/abs/10.1080/10705511.2013.742377
https://academiccommons.columbia.edu/download/fedora_content/download/ac:146638/content/Cheng_columbia_0054D_10722.pdf 

I'm not very familiar with IRT. Any approach that looks at interval coverage already sounds much more reasonable than treating individuals' latent variable scores as an observed variable. However, I get the impression from this reference that similar problems might exist in IRT, as the article describes that people commonly estimate latent variable scores by plugging in estimated model parameters and treating them as known population values: https://www.ncbi.nlm.nih.gov/pubmed/28879431

**Comment by datalorax** [comment]
Yeah, all that makes sense to me. But the issues that arise from that approach should be evident from the simulations. So I guess I'm just advocating that I think generating data from known processes and then evaluating the model's ability to recover those parameters is, from my perspective, generally always a good idea (assuming it is done well). It may not result in a publishable paper, but it can help to understand when the models do what you think they should and when they don't.

**Comment by jrosen48** [comment]
Hi all, thank you for your insights into this. For the models, what if the options were for *what is estimated and how*, instead of for the model names for? E.g., arguments for:

- `variances = c("freely-estimated", "fixed")`
- `covariances = c("freely-estimated", "fixed", "zero")`

Where fixed means that the parameter is the same across classes. 

Then, for the functions that compare a range of profile numbers and model specifications, we can index the four/six (there can be an option for *any* set of model specifications; I'd like to argue for four to be a sensible default, though I'm open to being argued that including all six is better).

**Comment by datalorax** [comment]
I think this is cleaner and more interpretable than model numbers.

**Comment by jrosen48** [comment]
if we did chose this, thoughts on the following verses the above (it's more concise, but to me a bit less accurate, grammatically):

- `variances = c("freed", "fixed")`
- `covariances = c("freed", "fixed", "zero")`

**Comment by datalorax** [comment]
Either works, I think, but I'd probably lean toward the latter.

**Comment by jrosen48** [comment]
This was addressed in #60
