### ISSUE TITLE
Including a variable in the dataset/VARIABLE command but not in the syntax for the model

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/tidyLPA#62]
I'm trying to include the option to account for the nesting/clustering of observations using MPlus. I'm trying to do this by specifying under the `VARIABLE` command a clustering variable with `Cluster = [name_of_var]` in conjunction with the `ANALYSIS` command `Type is complex;`.

I'm having some trouble because when I include the variable in the dataset (that is prepared in MPlus format), we use similar code to grab the names of the variables to be used for the analysis, and so in my first attempt or two I've ended up with profiles that include the clustering variable. That's not what I want. 

I noticed that we also include an ID variable (h/t @datalorax). However, this variable seems to avoid the fate of the clustering variable (i.e., it's *not* included in the clustering). I've reviewed the code but am having trouble solving this problem so I thought I would reach out. I think it's something to do in this (excerpted) code from the `estimate_profiles_mplus.R` file:

```
d <- select_ancillary_functions_mplus(df, ..., cluster_ID)
 if (is.null(idvar)) {
   id <- data_frame(id = as.numeric(rownames(df)))
   idvar <- "rownum"
 } else {
   if (length(unique(df[[idvar]])) != length(df[[idvar]])) {
     stop("ID variable must be unique")
   }
   if (is.character(df[[idvar]])) {
     string_id <- df[[idvar]]
     num_id <- seq_along(df[[idvar]])
     id <- data_frame(id = num_id)
     names(id) <- idvar
   }
   else {
     id <- data_frame(id = df[[idvar]])
     names(id) <- idvar
   }
 }
 d <- bind_cols(id, d)

 names(d) <- gsub("\\.", "_", names(d))

 x <- write_mplus(d, data_filename)

 var_list <- vector("list", ncol(d))
 for (i in seq_along(names(d))) {
   var_list[[i]] <- names(d)[i]
 }

```

Any ideas/tips would be much appreciated.

**Comment by datalorax** [comment]
I might be able to devote a little time to this in a bit. Are you expecting `cluster_ID` to be supplied as a string? And is `select_ancillary_functions_mplus(df, ..., cluster_ID)` working like you're expecting?

**Comment by jrosen48** [comment]
Thx much. So, I forgot I had added cluster_ID to that in my attempts; it wasn't throwing an error, I think, but it also wasn't working. I think one of the key lines I was missing was this:

`var_list <- var_list[-1]`

I think that removes the ID variable from the functions that generate/code that generates the MODEL syntax (in the section for the ANALYSIS part of the MPlus syntax). Does that sound right?

Dear gosh, I'm glad we're developing this, but working with MPlus code... makes me feel sad .

**Comment by jrosen48** [comment]
Also, yes, I was thinking as a string.

**Comment by jrosen48** [comment]
Alright, your code for the id variable was quite clear - I basically emulated it (with the added consideration that we now have two variables we potentially have to remove) and think that it works. The code needs to be cleaned up, so I'm going to leave this open until I do this.
