### ISSUE TITLE
[JOSS-Review] fix license.md

### ISSUE THREAD

**Issue by strengejacke** [jrosen48/tidyLPA#70]
This issue is related to https://github.com/openjournals/joss-reviews/issues/978.

Just a minor thing, please change "your name goes here" in https://github.com/jrosen48/tidyLPA/blob/master/LICENSE.md.

**Comment by jrosen48** [comment]
Thank you @strengejacke for this and your other very helpful feedback. I'm looking forward to addressing.

**Comment by jrosen48** [comment]
Fixed this.
