### ISSUE TITLE
[JOSS-Review] Add missing dois to paper

### ISSUE THREAD

**Issue by strengejacke** [jrosen48/tidyLPA#71]
This one is related to https://github.com/openjournals/joss-reviews/issues/978

There appear no DOIs in the paper's references. I assume that at least the cited journal articles have a DOI, so please check and add DOIs where available.

**Comment by jrosen48** [comment]
Thank you for noticing this - I checked each reference and added DOIs. Every reference now has at least a URL or a DOI.
