### ISSUE TITLE
[JOSS-review] clarify docs

### ISSUE THREAD

**Issue by strengejacke** [jrosen48/tidyLPA#72]
This one is related to https://github.com/openjournals/joss-reviews/issues/978

I just installed the package and tried out some functions. For `estimate_profiles()`, the help-file says, as return value
> either a tibble or a ggplot2 plot of the BIC values for the explored models

But I don't know how to create a ggplot-object. Could you clarify this in your docs, or help me finding the relevant passages in the help?

**Comment by jrosen48** [comment]
Thank you for diving in and catching this. I've added the following line to the documentation to replace the line you highlighted:

> either a tibble with the data and profile/class assignment and the posterior probability for that profile; the output of this function can be passed to the plot_profiles() function to create a ggplot2 plot of the profiles. If the argument to_return = "mclust" is added to the function call) an mclust model object, which can be inspected or plotted with mclust functions.

One way you can plot the profiles is something like:

```{r}
estimate_profiles(iris,
                  Sepal.Length, Sepal.Width, Petal.Length, Petal.Width,
                  n_profiles = 3) %>% 
    plot_profiles()
```

You could also (of course) save the output from `estimate_profiles()`, i.e.:

```{r}
m3 <- estimate_profiles(iris,
                  Sepal.Length, Sepal.Width, Petal.Length, Petal.Width,
                  n_profiles = 3)

plot_profiles(m3)
```

There are a few useful arguments to `plot_profiles()`, including the option to plot weighted (by the probability) means and to bootstrap the standard errors (h/t @cjvanlissa for this).

**Comment by strengejacke** [comment]
Looks good to me! Have you already committed the changes?

**Comment by jrosen48** [comment]
Just pushed--and made a minor change to the docs (changed in my comment above, too- I removed the word "either).
