### ISSUE TITLE
[JOSS-review] statement of need in readme.md

### ISSUE THREAD

**Issue by strengejacke** [jrosen48/tidyLPA#74]
This one is related to https://github.com/openjournals/joss-reviews/issues/978

While there's a clear statement of need in the paper, the _background_ section of the readme.md could elaborate a bit more on why tidyLPA is needed, also in the context of what already exists. It's just a minor issue, I would say adding a small sentence to the background should be OK.

**Comment by jrosen48** [comment]
Thank you for this helpful issue! I added the following to the second paragraph of the **Background** section of the README:

> The package is designed and documented to be easy to use, especially for beginners to LPA, but with fine-grained options available for estimating models and evaluating specific output as part of more complex analyses.
