### ISSUE TITLE
Editing plots

### ISSUE THREAD

**Issue by CG-Rodriguez** [jrosen48/tidyLPA#85]
I wonder if there's a way to edit the legends or the aesthetics of profile plots (size, color, align, etc.) within the `plot_profiles()` function -without editing it.

**Comment by jrosen48** [comment]
Hi, yes, there is a way - the plot is created with **ggplot2** and so any of the layers that can be added to a **ggplot2** plot can simply be added to the plot created with `plot_profiles()`.
