### ISSUE TITLE
parameters for variances and covariances don't seem to work

### ISSUE THREAD

**Issue by GerardYu** [jrosen48/tidyLPA#88]
I could not set the parameters for variance and covariance in both compare_solutions and estimate_solutions .

> compare_solutions(plan, init, exe, correct, models = list(c("equal", "zero"), c("varying", "zero"), c("equal","equal"), c("varying", "varying")))
Error: `list(c("equal", "zero"), c("varying", "zero"), c("equal", "equal"), 
    c("varying", "varying"))` must evaluate to column positions or names, not a list
In addition: Warning message:
'glue::collapse' is deprecated.
Use 'glue_collapse' instead.
See help("Deprecated") and help("glue-deprecated"). 

> estimate_profiles(plan, init, exe, correct, n_profiles=3, variances="zero")
Error: Unknown column `zero` 
In addition: Warning message:
'glue::collapse' is deprecated.
Use 'glue_collapse' instead.
See help("Deprecated") and help("glue-deprecated"). 

Also, i'm wondering if there is anyway to extract the entropy values?

**Comment by jrosen48** [comment]
Hi Gerard, are you using the latest CRAN version?

**Comment by GerardYu** [comment]
I'm using Microsoft R Open 3.51 , which is based on R-3.5.1

**Comment by jrosen48** [comment]
I'm sorry, I meant the version of the package (tidyLPA)

**Comment by GerardYu** [comment]
i did a fresh install of tidyLPA  (install.package("tidyLPA")) today, the same issues persist. checked my sessionInfo, its tidyLPA_0.1.3

**Comment by jrosen48** [comment]
Hi, hmm, it should be version 2.4. 
see here: https://cran.r-project.org/web/packages/tidyLPA/index.html

Can you try the following: devtools::install_github("jrosen48/tidyLPA", ref = "v0.2.4")

**Comment by GerardYu** [comment]
i see. thanks it worked now

**Comment by jrosen48** [comment]
Great!
